"""Tests for cem() — Coarsened Exact Matching for ATT weights.

Validated against Stata's ``cem`` SSC package (Blackwell, Iacus,
King, Porro 2009) on ``df_cem.csv`` with explicit cutpoints.

Two fixture layers:
  1. Stata-parity test: compares per-observation strata/weights/matched
     against a .dta generated by ``tests/stata/do/cem_basic.do``.
  2. Shape-and-sanity tests: built-in determinism check.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from open_econs.models.causal.balance import balance as _balance
from open_econs.models.causal.cem import cem

FIXTURE = "tests/stata/fixtures/df_cem.csv"
STATA_DTA = Path("tests/stata/do/cem_basic.dta")

# Expected values verified against Stata cem (see cem_basic.log):
#   Number of strata: 36
#   Number of matched strata: 32
EXPECTED = {
    "n_strata": 36,
    "n_mstrata": 32,
    "N_T_matched": 577,
    "N_C_matched": 414,
    "sum_w_t": 577.0,
    "sum_w_c": 414.0,
}

CUTPOINTS = {"x1": [-2, -1, 0, 1, 2], "x2": [0.5], "x3": "exact"}


@pytest.fixture
def df():
    return pd.read_csv(FIXTURE)


# ── Stata parity ─────────────────────────────────────────────

@pytest.mark.skipif(
    not STATA_DTA.exists(),
    reason="cem_basic.dta not found. Run 'tests/stata/do/cem_basic.do' in Stata.",
)
def test_cem_parity_with_stata(df):
    """Per-observation strata, weights, and matched flag match Stata."""
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    stata = pd.read_stata(STATA_DTA)

    assert (r.strata.values == stata["cem_strata"].values).all(), "strata mismatch"
    assert np.allclose(r.weights.values, stata["cem_weights"].values), "weights mismatch"
    assert (r.matched.values == stata["cem_matched"].values).all(), "matched mismatch"


# ── Summary statistics ───────────────────────────────────────

def test_cem_counts_match_stata(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    t = df["t"].values

    n_t_matched = int((t == 1 & r.matched.astype(bool)).sum())
    n_c_matched = int((t == 0 & r.matched.astype(bool)).sum())

    assert n_t_matched == EXPECTED["N_T_matched"]
    assert n_c_matched == EXPECTED["N_C_matched"]
    assert r.weights[t == 1].sum() == pytest.approx(EXPECTED["sum_w_t"])
    assert r.weights[t == 0].sum() == pytest.approx(EXPECTED["sum_w_c"])


def test_cem_strata_counts(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    n_strata = len(np.unique(r.strata.values))
    n_mstrata = len(np.unique(r.strata.values[r.matched.astype(bool)]))

    assert n_strata == EXPECTED["n_strata"]
    assert n_mstrata == EXPECTED["n_mstrata"]


# ── Result API shape ─────────────────────────────────────────

def test_cem_result_shape(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    assert isinstance(r.strata, pd.Series)
    assert isinstance(r.weights, pd.Series)
    assert isinstance(r.matched, pd.Series)
    assert len(r.strata) == len(df)
    assert len(r.weights) == len(df)
    assert len(r.matched) == len(df)


def test_cem_tidy_and_summary(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    tidy = r.tidy()
    assert isinstance(tidy, pd.DataFrame)
    assert "term" in tidy.columns
    assert "value" in tidy.columns
    assert isinstance(r.summary(), str)
    assert len(r.summary()) > 0


# ── Auto defaults ────────────────────────────────────────────

def test_cem_default_autocuts(df):
    """Smoke test: auto-Sturges (no cutpoints dict) runs without error."""
    r = cem(df, treatment="t")
    assert r.n_matched_strata >= 0
    assert r.weights.min() >= 0.0


# ── Invariants ───────────────────────────────────────────────

def test_cem_weight_properties(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    t = df["t"].values

    # Treated weights are exactly 1
    treated_matched = r.matched.astype(bool) & (t == 1)
    assert (r.weights.values[treated_matched] == 1.0).all()

    # Unmatched have weight 0
    unmatched = ~r.matched.astype(bool)
    assert (r.weights.values[unmatched] == 0.0).all()

    # All weights non-negative
    assert (r.weights.values >= 0.0).all()


# ── Balance delegation ───────────────────────────────────────

def test_cem_balance_delegation(df):
    """CEMResult.balance() matches direct balance() call with same inputs."""
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)

    result_bal = r.balance(covariates=["x1", "x2", "x3"])

    m = r.matched.values.astype(bool)
    data_m = df.iloc[m].copy()
    data_m["_cem_weights_"] = r.weights.values[m]
    direct_bal = _balance(
        data=data_m,
        treatment="t",
        covariates=["x1", "x2", "x3"],
        weights="_cem_weights_",
    )

    pd.testing.assert_frame_equal(result_bal, direct_bal)


def test_cem_balance_shape(df):
    """Smoke test: balance() returns expected columns."""
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    bal = r.balance(covariates=["x1", "x2", "x3"])
    assert "SMD" in bal.columns
    assert "Variance Ratio" in bal.columns
    assert len(bal) == 3  # x1, x2, x3
    assert bal["P>|t|"].is_monotonic_increasing  # sorted by p-value
