"""Tests for cem() — Coarsened Exact Matching for ATT weights.

Validated against Stata's ``cem`` SSC package (Blackwell, Iacus,
King, Porro 2009) on ``df_cem.csv`` with explicit cutpoints.

Two fixture layers:
  1. Stata-parity test: compares per-observation strata/weights/matched
     against a .dta generated by ``tests/stata/generate-fixtures/cem_basic.do``.
  2. Shape-and-sanity tests: built-in determinism check.

Formula-level tests for autocuts methods are in this file (hand-computable
cases, not Stata-dependent).  Full Stata-per-observation parity for all
four autocuts methods lives in ``tests/stata/test_stata_cem_autocuts.py``.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from open_econs.models.causal.balance import balance as _balance
from open_econs.models.causal.cem import (
    _fd_breaks,
    _scott_breaks,
    _ss_breaks,
    _sturges_breaks,
    cem,
)

FIXTURE = "tests/stata/fixtures/df_cem.csv"
STATA_DTA = Path("tests/stata/generate-fixtures/cem_basic.dta")

# Expected values verified against Stata cem (see cem_basic.log):
#   Number of strata: 36
#   Number of matched strata: 32
EXPECTED = {
    "n_strata": 36,
    "n_mstrata": 32,
    "N_T_matched": 577,
    "N_C_matched": 414,
    "sum_w_t": 577.0,
    "sum_w_c": 414.0,
}

CUTPOINTS = {"x1": [-2, -1, 0, 1, 2], "x2": [0.5], "x3": "exact"}


@pytest.fixture
def df():
    return pd.read_csv(FIXTURE)


# ── Stata parity ─────────────────────────────────────────────

@pytest.mark.stata
@pytest.mark.skipif(
    not STATA_DTA.exists(),
    reason="cem_basic.dta not found. Run 'tests/stata/generate-fixtures/cem_basic.do' in Stata.",
)
def test_cem_parity_with_stata(df):
    """Per-observation strata, weights, and matched flag match Stata."""
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    stata = pd.read_stata(STATA_DTA)

    assert (r.strata.values == stata["cem_strata"].values).all(), "strata mismatch"
    assert np.allclose(r.weights.values, stata["cem_weights"].values), "weights mismatch"
    assert (r.matched.values == stata["cem_matched"].values).all(), "matched mismatch"


# ── Summary statistics ───────────────────────────────────────

def test_cem_counts_match_stata(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    t = df["t"].values

    n_t_matched = int((t == 1 & r.matched.astype(bool)).sum())
    n_c_matched = int((t == 0 & r.matched.astype(bool)).sum())

    assert n_t_matched == EXPECTED["N_T_matched"]
    assert n_c_matched == EXPECTED["N_C_matched"]
    assert r.weights[t == 1].sum() == pytest.approx(EXPECTED["sum_w_t"])
    assert r.weights[t == 0].sum() == pytest.approx(EXPECTED["sum_w_c"])


def test_cem_strata_counts(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    n_strata = len(np.unique(r.strata.values))
    n_mstrata = len(np.unique(r.strata.values[r.matched.astype(bool)]))

    assert n_strata == EXPECTED["n_strata"]
    assert n_mstrata == EXPECTED["n_mstrata"]


# ── Result API shape ─────────────────────────────────────────

def test_cem_result_shape(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    assert isinstance(r.strata, pd.Series)
    assert isinstance(r.weights, pd.Series)
    assert isinstance(r.matched, pd.Series)
    assert len(r.strata) == len(df)
    assert len(r.weights) == len(df)
    assert len(r.matched) == len(df)


def test_cem_tidy_and_summary(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    tidy = r.tidy()
    assert isinstance(tidy, pd.DataFrame)
    assert "term" in tidy.columns
    assert "value" in tidy.columns
    assert isinstance(r.summary(), str)
    assert len(r.summary()) > 0


# ── Auto defaults ────────────────────────────────────────────

def test_cem_default_autocuts(df):
    """Smoke test: auto-Sturges (no cutpoints dict) runs without error."""
    r = cem(df, treatment="t")
    assert r.n_matched_strata >= 0
    assert r.weights.min() >= 0.0


# ── Invariants ───────────────────────────────────────────────

def test_cem_weight_properties(df):
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    t = df["t"].values

    # Treated weights are exactly 1
    treated_matched = r.matched.astype(bool) & (t == 1)
    assert (r.weights.values[treated_matched] == 1.0).all()

    # Unmatched have weight 0
    unmatched = ~r.matched.astype(bool)
    assert (r.weights.values[unmatched] == 0.0).all()

    # All weights non-negative
    assert (r.weights.values >= 0.0).all()


# ── Balance delegation ───────────────────────────────────────

def test_cem_balance_delegation(df):
    """CEMResult.balance() matches direct balance() call with same inputs."""
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)

    result_bal = r.balance(covariates=["x1", "x2", "x3"])

    m = r.matched.values.astype(bool)
    data_m = df.iloc[m].copy()
    data_m["_cem_weights_"] = r.weights.values[m]
    direct_bal = _balance(
        data=data_m,
        treatment="t",
        covariates=["x1", "x2", "x3"],
        weights="_cem_weights_",
    )

    pd.testing.assert_frame_equal(result_bal, direct_bal)


def test_cem_balance_shape(df):
    """Smoke test: balance() returns expected columns."""
    r = cem(df, treatment="t", covariates=["x1", "x2", "x3"], cutpoints=CUTPOINTS)
    bal = r.balance(covariates=["x1", "x2", "x3"])
    assert "SMD" in bal.columns
    assert "Variance Ratio" in bal.columns
    assert len(bal) == 3  # x1, x2, x3
    assert bal["P>|t|"].is_monotonic_increasing  # sorted by p-value


# ── Autocuts formula correctness (hand-computable, Stata-independent) ──

class TestAutocutsFormulas:
    """Each breakpoint function is checked against a hand-computed
    reference or an independently derived numpy/scipy calculation.
    Not a Stata parity claim — these verify the arithmetic is correct.
    """

    def test_sturges_formula(self):
        x = np.arange(100.0)
        breaks = _sturges_breaks(x)
        k = int(np.ceil(np.log2(100) + 1))
        assert len(breaks) == k, f"Sturges: expected {k} breakpoints, got {len(breaks)}"
        np.testing.assert_array_almost_equal(breaks, np.linspace(0, 99, k))

    def test_sturges_small_n(self):
        """n=2 => ceil(log2(2)+1) = ceil(2) = 2 breakpoints (1 bin)."""
        x = np.array([0.0, 1.0])
        breaks = _sturges_breaks(x)
        k = int(np.ceil(np.log2(2) + 1))
        assert len(breaks) == k, f"Sturges n=2: expected {k} breakpoints, got {len(breaks)}"

    def test_fd_formula(self):
        """Linear sequence: IQR=50, h=2*50*100^(-1/3)=21.54, ceil(99/21.54)=5 breakpoints."""
        x = np.arange(100.0)
        breaks = _fd_breaks(x)
        q75, q25 = np.percentile(x, [75, 25])
        iqr = q75 - q25
        h = 2.0 * iqr * 100.0 ** (-1.0 / 3.0)
        expected_k = max(int(np.ceil(99.0 / h)), 2)
        assert len(breaks) == expected_k, f"FD: expected {expected_k} breakpoints, got {len(breaks)}"
        np.testing.assert_array_almost_equal(breaks, np.linspace(0, 99, expected_k))

    def test_fd_mad_fallback_all_equal(self):
        """All-equal data: IQR=0 and MAD=0 → FD returns 2 breakpoints (1 bin)."""
        x = np.ones(50) * 5.0
        breaks = _fd_breaks(x)
        assert len(breaks) == 2

    def test_fd_hand_computed(self):
        """Verify FD formula independently for a small known case."""
        x = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])
        q75, q25 = np.percentile(x, [75, 25])
        iqr = q75 - q25
        h = 2.0 * iqr * 10.0 ** (-1.0 / 3.0)
        expected_k = max(int(np.ceil(9.0 / h)), 2)
        breaks = _fd_breaks(x)
        assert len(breaks) == expected_k

    def test_fd_all_equal(self):
        """All-equal data: IQR=0, MAD=0 → returns 2 breakpoints (1 bin)."""
        x = np.ones(50) * 5.0
        breaks = _fd_breaks(x)
        assert len(breaks) == 2

    def test_scott_formula(self):
        """Linear sequence: std≈29.01, h=3.5*29.01*100^(-1/3)=21.87, ceil(99/21.87)=5 breakpoints."""
        x = np.arange(100.0)
        breaks = _scott_breaks(x)
        h = 3.5 * x.std(ddof=1) * 100.0 ** (-1.0 / 3.0)
        expected_k = max(int(np.ceil(99.0 / h)), 2)
        assert len(breaks) == expected_k, f"Scott: expected {expected_k} breakpoints, got {len(breaks)}"
        np.testing.assert_array_almost_equal(breaks, np.linspace(0, 99, expected_k))

    def test_ss_formula(self):
        """Verify SS runs and returns a plausible number of breakpoints.

        For N(0,1) data with n=500, SS should pick more than 2 breakpoints
        (i.e. at least 2 bins), matching the fact that the standard normal
        is spread across a range that supports multiple bins.
        """
        rng = np.random.default_rng(42)
        x = rng.normal(0, 1, 500)
        breaks = _ss_breaks(x)
        assert len(breaks) >= 2
        assert len(breaks) <= 100


# ── Autocuts integration tests ─────────────────────────────────

@pytest.fixture
def df_autocuts():
    return pd.read_csv("tests/stata/fixtures/df_cem_autocuts.csv")


def test_cem_autocuts_smoke(df_autocuts):
    """Each autocuts method runs without error and produces consistent output."""
    t = df_autocuts["t"].values
    for method in ["sturges", "fd", "scott", "ss"]:
        r = cem(df_autocuts, treatment="t", covariates=["x1", "x2", "x3"],
                autocuts=method)
        assert r.n_matched_strata >= 0
        assert r.weights.min() >= 0.0
        treated_matched = r.matched.astype(bool) & (t == 1)
        assert (r.weights.values[treated_matched] == 1.0).all()
        unmatched = ~r.matched.astype(bool)
        assert (r.weights.values[unmatched] == 0.0).all()
        assert "Auto-coarsening method" in r.summary()


def test_cem_autocuts_summary_shows_method(df_autocuts):
    r = cem(df_autocuts, treatment="t", autocuts="fd")
    assert "fd" in r.summary()


def test_cem_autocuts_cutpoints_override(df_autocuts):
    """Per-variable cutpoints override the global autocuts default."""
    r = cem(df_autocuts, treatment="t", covariates=["x1", "x2", "x3"],
            cutpoints={"x1": "fd"}, autocuts="sturges")
    # x1 uses FD, x2 and x3 use Sturges
    assert r.n_matched_strata >= 0


def test_cem_autocuts_invalid_method(df_autocuts):
    import re
    with pytest.raises(ValueError, match=re.escape("Unknown binning method")):
        cem(df_autocuts, treatment="t", autocuts="invalid")


def test_cem_autocuts_export(df_autocuts):
    r = cem(df_autocuts, treatment="t", autocuts="scott")
    d = r.to_dict()
    assert d["autocuts"] == "scott"
    assert "breakpoints" in d
