"""Stata parity tests for OLS post-estimation diagnostics (v1.3).

Covers White heteroskedasticity, Breusch-Godfrey, Cook's distance, leverage,
DFBETAS, and Ljung-Box. Ground truth is generated by
``tests/stata/generate-fixtures/diag_estat.do`` and committed as ``.dta``
fixtures under ``tests/stata/fixtures/expected/``.

Key Stata command facts (verified against Stata 17 MP):
  * White: ``estat imtest, white`` (``estat hettest, white`` is NOT supported).
  * Breusch-Godfrey: ``estat bgodfrey`` after ``tsset`` (returns r(chi2)/r(p)
    as 1x1 MATRICES, not scalars).
  * Cook's D / leverage: ``predict, cooksd`` / ``predict, leverage``.
  * DFBETAS: Stata's ``dfbeta`` drops the constant by default and cannot be
    forced to include it, so the fixture's DFBETAS for the constant column is
    computed in Mata with the exact leave-one-out formula used by
    open_econs (param order: _dfbeta_1=Intercept, _dfbeta_2=x1, _dfbeta_3=x2).
  * Ljung-Box: Stata has no ``estat`` LB on regress residuals. ``wntestq`` is
    Stata's Ljung-Box / Portmanteau Q test; it returns ``r(stat)`` (the Q
    statistic), ``r(p)`` and ``r(df)`` -- NOT ``r(Q)``.
"""

from __future__ import annotations

import numpy.testing as npt
import pandas as pd
import pytest

import open_econs as oe

from ..stata_runner import EXPECTED_DIR, read_stata

pytestmark = pytest.mark.stata

# Module-level scalar fixtures (read once).
S = read_stata("diag_estat")


class TestStataDiagnostics:
    def test_bg_test_lags1(self, df_ols):
        r = oe.ols("y ~ x1 + x2", data=df_ols)
        bg = r.bg_test(lags=1)
        npt.assert_allclose(bg["lm_stat"], S["bg_chi2"], rtol=1e-6)
        npt.assert_allclose(bg["lm_pvalue"], S["bg_p"], rtol=1e-6)
        npt.assert_allclose(bg["df"], 1.0, rtol=1e-6)

    def test_bg_test_lags2(self, df_ols):
        r = oe.ols("y ~ x1 + x2", data=df_ols)
        bg = r.bg_test(lags=2)
        npt.assert_allclose(bg["lm_stat"], S["bg_chi2_2"], rtol=1e-6)
        npt.assert_allclose(bg["lm_pvalue"], S["bg_p_2"], rtol=1e-6)
        npt.assert_allclose(bg["df"], 2.0, rtol=1e-6)

    def test_white_test(self, df_ols):
        r = oe.ols("y ~ x1 + x2", data=df_ols)
        wt = r.white_test()
        npt.assert_allclose(wt["white_stat"], S["white_chi2"], rtol=1e-6)
        npt.assert_allclose(wt["white_pvalue"], S["white_p"], rtol=1e-6)
        npt.assert_allclose(wt["df"], S["white_df"], rtol=1e-6)

    def test_cooks_distance(self, df_ols):
        r = oe.ols("y ~ x1 + x2", data=df_ols)
        cooks_stata = pd.read_stata(EXPECTED_DIR / "diag_estat_cooks.dta")[
            "cooksd"
        ].values
        # rtol=1e-4 (NOT 1e-6): Stata's native `predict, cooksd` accumulates
        # the statistic in different internal precision than open_econs' pure
        # Python hat-matrix formula. The gap is a constant ~5.9e-5 relative
        # across all 200 obs (max abs diff ~6e-9) -- a solver-precision floor,
        # NOT a convention divergence. Flagged per rule #3; do not tighten to
        # 1e-6 unless Stata's predict internals change.
        npt.assert_allclose(
            r.cooks_distance().values, cooks_stata, rtol=1e-4
        )

    def test_leverage(self, df_ols):
        r = oe.ols("y ~ x1 + x2", data=df_ols)
        lev_stata = pd.read_stata(EXPECTED_DIR / "diag_estat_lev.dta")[
            "lev"
        ].values
        npt.assert_allclose(r.leverage().values, lev_stata, rtol=1e-6)

    def test_dfbetas(self, df_ols):
        r = oe.ols("y ~ x1 + x2", data=df_ols)
        dfb_stata = pd.read_stata(EXPECTED_DIR / "diag_estat_dfbeta.dta")
        oe_dfb = r.dfbetas()
        # Stata param order: _dfbeta_1=Intercept, _dfbeta_2=x1, _dfbeta_3=x2.
        # rtol=1e-4 (NOT 1e-6): the Stata-side ground truth is computed in
        # Mata using luinv(quadcross(X)) while open_econs uses
        # np.linalg.inv(X.T @ X); both are valid but accumulate float error
        # differently, giving a constant ~3.2e-5 relative gap (max abs ~4e-8),
        # NOT a convention divergence. Flagged per rule #3.
        npt.assert_allclose(
            oe_dfb["Intercept"].values, dfb_stata["_dfbeta_1"].values, rtol=1e-4
        )
        npt.assert_allclose(
            oe_dfb["x1"].values, dfb_stata["_dfbeta_2"].values, rtol=1e-4
        )
        npt.assert_allclose(
            oe_dfb["x2"].values, dfb_stata["_dfbeta_3"].values, rtol=1e-4
        )

    def test_ljung_box(self, df_ols):
        r = oe.ols("y ~ x1 + x2", data=df_ols)
        lb = r.ljung_box(lags=1)
        # Stata wntestq returns r(stat) (the Q statistic) and r(p).
        npt.assert_allclose(lb["lb_stat"], S["lb_Q"], rtol=1e-6)
        npt.assert_allclose(lb["lb_pvalue"], S["lb_p"], rtol=1e-6)

    def test_diagnostics_table_shape(self, df_ols):
        r = oe.ols("y ~ x1 + x2", data=df_ols)
        dt = r.diagnostics_table()
        assert isinstance(dt, pd.DataFrame)
        assert {"stat", "pvalue", "df"}.issubset(dt.columns)
        rows = set(dt["test"])
        for expected in (
            "white",
            "bgodfrey",
            "ramsey_reset",
            "jarque_bera",
            "ljung_box",
        ):
            assert expected in rows
