"""Stata parity tests for ``oe.ologit`` / ``oe.oprobit``.

Source-verified against Stata base ``ologit`` / ``oprobit`` (dropping the FIRST
category as reference, matching R ``MASS::polr`` default). Coefficients,
cutpoints (thresholds), log-likelihood, and OIM standard errors match Stata to
``1e-6`` (the statsmodels MLE is high-precision-polished in the backend so it
reaches Stata's optimizer precision; see ``methodology/limited/ordered.md``).

Fixture: ``tests/stata/fixtures/expected/ordered.dta`` (generated by
``tests/stata/generate-fixtures/ordered.do``). Shared input:
``tests/r/fixtures/inputs/ordered_input.csv``.

Stata fixture keys (ologit / oprobit share the pattern via the ``ologit_`` /
``oprobit_`` prefix):
    b_x1, b_x2, b_x3        coefficient point estimates
    cut1, cut2, cut3        cumulative threshold (cutpoint) parameters
    se_x1, se_x2, se_x3     OIM standard errors
    ll                      log-likelihood
    ser_x1..ser_x3          robust (HC1) SEs of ologit (match to 1e-6)

All non-robust assertions at ``atol=1e-6`` — nothing loosened (rule 2).
"""

from __future__ import annotations

import numpy.testing as npt
import pandas as pd
import pytest

import open_econs as oe

from ..stata_runner import read_stata

pytestmark = pytest.mark.stata

STATA = read_stata("ordered")
DF = pd.read_csv("tests/r/fixtures/inputs/ordered_input.csv")


class TestStataOrderedLogit:
    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_coef(self, x):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.coefficients[x], STATA[f"ologit_b_{x}"], rtol=0, atol=1e-6)

    @pytest.mark.parametrize("c", ["cut1", "cut2", "cut3"])
    def test_cutpoint(self, c):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.cutpoints[c], STATA[f"ologit_{c}"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.llf, STATA["ologit_ll"], rtol=0, atol=1e-6)

    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_oim_se(self, x):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.std_errors[x], STATA[f"ologit_se_{x}"], rtol=0, atol=1e-6)


class TestStataOrderedProbit:
    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_coef(self, x):
        r = oe.oprobit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.coefficients[x], STATA[f"oprobit_b_{x}"], rtol=0, atol=1e-6)

    @pytest.mark.parametrize("c", ["cut1", "cut2", "cut3"])
    def test_cutpoint(self, c):
        r = oe.oprobit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.cutpoints[c], STATA[f"oprobit_{c}"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = oe.oprobit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.llf, STATA["oprobit_ll"], rtol=0, atol=1e-6)

    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_oim_se(self, x):
        r = oe.oprobit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.std_errors[x], STATA[f"oprobit_se_{x}"], rtol=0, atol=1e-6)


class TestStataOrderedRobustSE:
    """Stata ``ologit, vce(robust)`` parity (CLOSED): OE's HC1 robust SE matches
    Stata ``ologit, vce(robust)`` to ``1e-6``. Root cause (FUTURE_WORK.md /
    ``methodology/limited/ordered.md`` open gap 4) was the numerical-score bread:
    OE now uses Stata's exact OIM bread ``inv(-H)`` with the EXACT analytical
    observation scores (over the full ``(β, cut1..)`` vector in Stata's
    cumulative-cutpoint parameterization) and Stata's ``n/(n-1)`` small-sample
    factor. The OIM (nonrobust) SE — the original validated deliverable — is
    unchanged and still matches to ``1e-6`` (TestStataOrderedLogit.test_oim_se).
    """

    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_robust_se_x(self, x):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF, cov_type="HC1")
        npt.assert_allclose(r.std_errors[x], STATA[f"ologit_ser_{x}"], rtol=0, atol=1e-6)
