"""Stata parity tests for ``oe.ologit`` / ``oe.oprobit``.

Source-verified against Stata base ``ologit`` / ``oprobit`` (dropping the FIRST
category as reference, matching R ``MASS::polr`` default). Coefficients,
cutpoints (thresholds), log-likelihood, and OIM standard errors match Stata to
``1e-6`` (the statsmodels MLE is high-precision-polished in the backend so it
reaches Stata's optimizer precision; see ``methodology/limited/ordered.md``).

Fixture: ``tests/stata/fixtures/expected/ordered.dta`` (generated by
``tests/stata/generate-fixtures/ordered.do``). Shared input:
``tests/r/fixtures/inputs/ordered_input.csv``.

Stata fixture keys (ologit / oprobit share the pattern via the ``ologit_`` /
``oprobit_`` prefix):
    b_x1, b_x2, b_x3        coefficient point estimates
    cut1, cut2, cut3        cumulative threshold (cutpoint) parameters
    se_x1, se_x2, se_x3     OIM standard errors
    ll                      log-likelihood
    ser_x1..ser_x3          robust (HC1) SEs of ologit (OPEN GAP, see below)

All non-robust assertions at ``atol=1e-6`` — nothing loosened (rule 2).
"""

from __future__ import annotations

import numpy.testing as npt
import pandas as pd
import pytest

import open_econs as oe

from ..stata_runner import read_stata

pytestmark = pytest.mark.stata

STATA = read_stata("ordered")
DF = pd.read_csv("tests/r/fixtures/inputs/ordered_input.csv")


class TestStataOrderedLogit:
    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_coef(self, x):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.coefficients[x], STATA[f"ologit_b_{x}"], rtol=0, atol=1e-6)

    @pytest.mark.parametrize("c", ["cut1", "cut2", "cut3"])
    def test_cutpoint(self, c):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.cutpoints[c], STATA[f"ologit_{c}"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.llf, STATA["ologit_ll"], rtol=0, atol=1e-6)

    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_oim_se(self, x):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.std_errors[x], STATA[f"ologit_se_{x}"], rtol=0, atol=1e-6)


class TestStataOrderedProbit:
    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_coef(self, x):
        r = oe.oprobit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.coefficients[x], STATA[f"oprobit_b_{x}"], rtol=0, atol=1e-6)

    @pytest.mark.parametrize("c", ["cut1", "cut2", "cut3"])
    def test_cutpoint(self, c):
        r = oe.oprobit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.cutpoints[c], STATA[f"oprobit_{c}"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = oe.oprobit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.llf, STATA["oprobit_ll"], rtol=0, atol=1e-6)

    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_oim_se(self, x):
        r = oe.oprobit("y ~ x1 + x2 + x3", data=DF)
        npt.assert_allclose(r.std_errors[x], STATA[f"oprobit_se_{x}"], rtol=0, atol=1e-6)


class TestStataOrderedRobustSE:
    """OPEN PARITY GAP (rule 6/15/16 — do NOT loosen): OE's HC1 robust SE for
    ordered models diverges from Stata ``ologit, vce(robust)`` by ~4e-4. Same
    root cause as the poisson non-clustered robust gap: the numerical
    score/hessian bread differs from Stata's exact OIM bread at machine
    precision, and Stata's robust factor uses its own small-sample
    convention. The OIM (nonrobust) SE — the validated deliverable — matches to
    1e-6 (TestStataOrderedLogit.test_oim_se). Recorded in FUTURE_WORK.md and
    ``methodology/limited/ordered.md``.
    """

    @pytest.mark.xfail(
        reason="OPEN GAP (FUTURE_WORK.md L459b): ologit HC1 robust SE diverges "
               "from Stata vce(robust) by ~4e-4 (numerical-score bread vs Stata "
               "exact OIM robust bread + small-sample factor). OIM SE parity is "
               "validated in TestStataOrderedLogit.test_oim_se. Asserting OE HC1 "
               "SE vs Stata ser captures ~4e-4 > 1e-6, so it xfails. strict=True: "
               "errors if it ever matches to 1e-6.",
        strict=True,
    )
    @pytest.mark.parametrize("x", ["x1", "x2", "x3"])
    def test_robust_se_x(self, x):
        r = oe.ologit("y ~ x1 + x2 + x3", data=DF, cov_type="HC1")
        npt.assert_allclose(r.std_errors[x], STATA[f"ologit_ser_{x}"], rtol=0, atol=1e-6)
