"""Stata parity tests for ``oe.tobit`` (hand-rolled censored-normal MLE).

Source-verified against Stata base ``tobit``. ``oe.tobit`` matches Stata to
``1e-6`` on the point estimates, ``sigma`` (Stata prints ``Log(scale)`` =
``ln(sigma)``; the stored ``sigma`` here is ``sqrt(e(b)[5])`` because Stata
reports ``var(e.y)`` = ``sigma^2`` as the 5th ``e(b)`` element), the OIM
(nonrobust) standard errors, and the log-likelihood.

Fixtures: ``tests/stata/fixtures/expected/tobit.dta`` (generated by
``tests/stata/generate-fixtures/tobit.do``). Shared input:
``tests/r/fixtures/inputs/tobit_input.csv``.

Stata fixture keys (left-censored at 0):
    b_x1, b_x2, b_x3         point estimates (x1, x2, x3)
    se_x1, se_x2, se_x3      OIM (nonrobust) SEs
    sigma_l                  sigma (= sqrt(var(e.y)))
    logscale_l               ln(sigma) == Stata "Log(scale)"
    ll_l                     log-likelihood
    n_left_l                 left-censored obs count
No-censoring variant (keys prefixed ``b2_``, ``se2_``, ``sigma2``, ``ll2``):
    Stata tobit with ll(-1e15) ul(1e15) -> OLS-equivalent MLE.

All assertions at ``atol=1e-6`` — nothing loosened (rule 2). Robust/cluster SEs
for Tobit are a documented open gap (numerical-score sandwich diverges from
Stata's exact OIM robust bread by ~1e-4); see FUTURE_WORK.md. Only OIM is
asserted here.
"""

from __future__ import annotations

import numpy.testing as npt
import pandas as pd
import pytest

from open_econs.models.limited.tobit import tobit

from ..stata_runner import read_stata

pytestmark = pytest.mark.stata

STATA = read_stata("tobit")
DF = pd.read_csv("tests/r/fixtures/inputs/tobit_input.csv")


class TestStataTobitLeftCensored:
    """Left-censored (ll(0)) Tobit: coefs / sigma / OIM SE / ll."""

    def test_b_x1(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.coefficients["x1"], STATA["b_x1"], rtol=0, atol=1e-6)

    def test_b_x2(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.coefficients["x2"], STATA["b_x2"], rtol=0, atol=1e-6)

    def test_b_x3(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.coefficients["x3"], STATA["b_x3"], rtol=0, atol=1e-6)

    def test_sigma(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.sigma, STATA["sigma_l"], rtol=0, atol=1e-6)

    def test_log_scale(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.log_scale, STATA["logscale_l"], rtol=0, atol=1e-6)

    def test_se_x1(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.std_errors["x1"], STATA["se_x1"], rtol=0, atol=1e-6)

    def test_se_x2(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.std_errors["x2"], STATA["se_x2"], rtol=0, atol=1e-6)

    def test_se_x3(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.std_errors["x3"], STATA["se_x3"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.llf, STATA["ll_l"], rtol=0, atol=1e-6)

    def test_n_left(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        assert r.n_left == int(STATA["n_left_l"])


class TestStataTobitNoCensoring:
    """No-censoring variant: Stata tobit ll(-1e15) ul(1e15) ~ OLS MLE."""

    def test_b_x1(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.coefficients["x1"], STATA["b2_x1"], rtol=0, atol=1e-6)

    def test_b_x2(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.coefficients["x2"], STATA["b2_x2"], rtol=0, atol=1e-6)

    def test_b_x3(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.coefficients["x3"], STATA["b2_x3"], rtol=0, atol=1e-6)

    def test_sigma(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.sigma, STATA["sigma2"], rtol=0, atol=1e-6)

    def test_se_x1(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.std_errors["x1"], STATA["se2_x1"], rtol=0, atol=1e-6)

    def test_se_x2(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.std_errors["x2"], STATA["se2_x2"], rtol=0, atol=1e-6)

    def test_se_x3(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.std_errors["x3"], STATA["se2_x3"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.llf, STATA["ll2"], rtol=0, atol=1e-6)


class TestStataTobitRobustClusterGap:
    """OPEN GAP (rule 2/15/16 — do NOT loosen): ``oe.tobit`` robust/cluster SEs
    are computed by a numerical-score sandwich (per-obs Jacobian) that diverges
    from Stata ``tobit``'s exact OIM-robust bread by ~1e-4 (same class of issue
    as poisson/ologit). The OIM (nonrobust) SE is the validated deliverable and
    is asserted in TestStataTobitLeftCensored / TestStataTobitNoCensoring above.

    No Stata robust/cluster tobit fixture is committed yet (the .do generator
    emits OIM only), so these are skipped with a documented reason rather than
    fabricated. They exist so the open gap is collected and visible (not silently
    passing) until a Stata robust fixture is generated. See FUTURE_WORK.md and
    methodology/limited/tobit.md A3."""

    @pytest.mark.xfail(
        reason="OPEN GAP (FUTURE_WORK.md L493): oe.tobit cov_type='HC1' robust SE "
               "diverges from Stata tobit vce(robust) exact OIM-robust bread by "
               "~1e-4 (numerical-score sandwich vs analytic bread). No committed "
               "Stata robust fixture exists, so the assertion compares the HC1 SE "
               "against Stata's OIM SE (se_x1); they genuinely differ >1e-6, so it "
               "xfails. strict=True: errors if it ever matches to 1e-6. OIM parity "
               "is validated above. See methodology/limited/tobit.md A3.",
        strict=True,
    )
    def test_robust_se_x1(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0, cov_type="HC1")
        npt.assert_allclose(r.std_errors["x1"], STATA["se_x1"], rtol=0, atol=1e-6)

    @pytest.mark.xfail(
        reason="OPEN GAP (FUTURE_WORK.md L493): same as test_robust_se_x1 (tobit "
               "HC1 robust SE vs Stata OIM SE, ~1e-4). strict=True.",
        strict=True,
    )
    def test_robust_se_x2(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0, cov_type="HC1")
        npt.assert_allclose(r.std_errors["x2"], STATA["se_x2"], rtol=0, atol=1e-6)

    @pytest.mark.xfail(
        reason="OPEN GAP (FUTURE_WORK.md L493): oe.tobit cluster-robust SE "
               "diverges from Stata tobit cluster-robust by ~1e-4 (numerical-score "
               "sandwich vs exact OIM bread). NOTE: tobit_input.csv has NO cluster "
               "'id' column and no committed Stata cluster fixture exists, so the "
               "cluster-specific call is not run here; instead we assert the "
               "available robust (HC1) SE against Stata's OIM SE (se_x1) to capture "
               "the same robust-vs-OIM divergence class (~1e-4), which genuinely "
               "differs >1e-6 and xfails. strict=True. Needs a proper Stata "
               "vce(cluster ...) fixture + id column to tighten the cluster path.",
        strict=True,
    )
    def test_cluster_se_x1(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0, cov_type="HC1")
        npt.assert_allclose(r.std_errors["x1"], STATA["se_x1"], rtol=0, atol=1e-6)
