"""Stata parity tests for ``oe.poisson`` (FE-backed Poisson PPML).

Source-verified against Stata SSC ``ppmlhdfe`` (Correia, Guimaraes & Zylkin
2020, v2.3.3). ``oe.poisson`` matches ``ppmlhdfe`` when run with
``vcov_backend="stata"`` (rule 15 toggle): that branch applies
``ssc(k_adj=False, G_adj=True, k_fixef="none")`` which reproduces ppmlhdfe's
cluster and iid small-sample factors to 1e-6.

Fixture: ``tests/stata/fixtures/expected/poisson.dta`` (generated by
``tests/stata/generate-fixtures/poisson.do``). Shared input:
``tests/r/fixtures/inputs/poisson_input.csv``.

Stata fixture keys:
    b_x1, b_x2        point estimates
    se_x1_clu, se_x2_clu  cluster(firm) SEs (ppmlhdfe default)
    se_x1_iid, se_x2_iid  nonrobust (iid) SEs
    ll_clu            log pseudolikelihood
    dev_clu           deviance

All assertions at ``atol=1e-6`` — nothing loosened (rule 2). The fixest/R
branch is validated separately in ``tests/r/tests/test_r_poisson.py``.
"""

from __future__ import annotations

import numpy.testing as npt
import pandas as pd
import pytest

from open_econs.models.limited.poisson import poisson

from ..stata_runner import read_stata

pytestmark = pytest.mark.stata

STATA = read_stata("poisson")
DF = pd.read_csv("tests/r/fixtures/inputs/poisson_input.csv")


class TestStataPoissonCoefficients:
    """Point estimates match ppmlhdfe (identical across tools)."""

    def test_b_x1(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm",
                    vcov_backend="stata")
        npt.assert_allclose(r.coefficients["x1"], STATA["b_x1"], rtol=0, atol=1e-6)

    def test_b_x2(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm",
                    vcov_backend="stata")
        npt.assert_allclose(r.coefficients["x2"], STATA["b_x2"], rtol=0, atol=1e-6)


class TestStataPoissonClusterSE:
    """oe vcov_backend='stata' cluster(firm) SEs match ppmlhdfe default."""

    def test_se_x1(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm",
                    vcov_backend="stata")
        npt.assert_allclose(r.std_errors["x1"], STATA["se_x1_clu"], rtol=0, atol=1e-6)

    def test_se_x2(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm",
                    vcov_backend="stata")
        npt.assert_allclose(r.std_errors["x2"], STATA["se_x2_clu"], rtol=0, atol=1e-6)


class TestStataPoissonIidSE:
    """oe vcov_backend='stata' non-clustered SEs vs ppmlhdfe *non-clustered* SEs.

    ppmlhdfe without ``cluster()`` reports a *robust (sandwich)* SE, not an OIM
    iid SE. ``oe.poisson(..., vcov_backend="stata", cluster=None)`` wraps
    ppmlhdfe's exact nonlinear-Poisson (Correia-Guimaraes-Zylkin 2019) robust
    meat — ``meat = Σ_i (y_i − μ_i)^2 / μ_i · x_i x_i'`` with the OIM bread and
    the ``k_adj = (N−1)/(N−K)`` small-sample factor — so it matches ppmlhdfe's
    non-clustered SE to 1e-6 (rule 15 option a). The cluster-robust SE — the
    headline PPML use case — is matched to 1e-6 in TestStataPoissonClusterSE.
    See methodology/limited/poisson.md §2.4.
    """

    def test_se_x1(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"],
                    cov_type="nonrobust", vcov_backend="stata")
        npt.assert_allclose(r.std_errors["x1"], STATA["se_x1_iid"], rtol=0, atol=1e-6)

    def test_se_x2(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"],
                    cov_type="nonrobust", vcov_backend="stata")
        npt.assert_allclose(r.std_errors["x2"], STATA["se_x2_iid"], rtol=0, atol=1e-6)


class TestStataPoissonFitStats:
    """Deviance / log pseudolikelihood identical to ppmlhdfe."""

    def test_deviance(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm",
                    vcov_backend="stata")
        npt.assert_allclose(r.deviance, STATA["dev_clu"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm",
                    vcov_backend="stata")
        npt.assert_allclose(r.llf, STATA["ll_clu"], rtol=0, atol=1e-6)
