"""R parity tests for ``oe.poisson`` (FE-backed Poisson PPML).

Source-verified against R ``fixest::fepois`` (Berge 2018). Both the fixest
default and the ppmlhdfe-equivalent small-sample conventions are validated,
because ``oe.poisson`` exposes the ``vcov_backend`` toggle (rule 15) and each
branch must match its own reference engine to 1e-6.

Fixture: ``tests/r/fixtures/expected/poisson.json`` (generated by
``tests/r/generate-fixtures/poisson.R``). Shared input:
``tests/r/fixtures/inputs/poisson_input.csv``.

Keys in the fixture:
    b_x1, b_x2                  point estimates (identical across all tools)
    se_x1_fixest, se_x2_fixest  fepois default ssc  -> oe vcov_backend="fixest"
    se_x1_stata,  se_x2_stata   ssc(fixef.K=none, adj=FALSE, cluster.adj=TRUE)
                                -> oe vcov_backend="stata" (== Stata ppmlhdfe)
    se_x1_iid,    se_x2_iid     nonrobust (iid) SEs (fixest convention)
    deviance, loglik, pseudo_r2 McFadden pseudo-R2 (fixest _pseudo_r2)

All assertions at ``atol=1e-6`` — nothing loosened (rule 2).
"""

from __future__ import annotations

import numpy as np
import numpy.testing as npt
import pandas as pd
import pytest

from open_econs.models.limited.poisson import poisson

from ..r_runner import read_r

pytestmark = pytest.mark.r

R = read_r("poisson")
DF = pd.read_csv("tests/r/fixtures/inputs/poisson_input.csv")


class TestRPoissonCoefficients:
    """Point estimates match R fixest::fepois (no convention difference)."""

    def test_b_x1(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"])
        npt.assert_allclose(r.coefficients["x1"], R["b_x1"], rtol=0, atol=1e-6)

    def test_b_x2(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"])
        npt.assert_allclose(r.coefficients["x2"], R["b_x2"], rtol=0, atol=1e-6)


class TestRPoissonFixestBackend:
    """oe vcov_backend='fixest' (default) matches R fepois defaults + iid."""

    def test_cluster_se(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm")
        npt.assert_allclose(r.std_errors["x1"], R["se_x1_fixest"], rtol=0, atol=1e-6)
        npt.assert_allclose(r.std_errors["x2"], R["se_x2_fixest"], rtol=0, atol=1e-6)

    def test_iid_se(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cov_type="nonrobust")
        npt.assert_allclose(r.std_errors["x1"], R["se_x1_iid"], rtol=0, atol=1e-6)
        npt.assert_allclose(r.std_errors["x2"], R["se_x2_iid"], rtol=0, atol=1e-6)


class TestRPoissonStataBackend:
    """oe vcov_backend='stata' matches R fepois ssc(fixef.K=none,adj=FALSE,cluster.adj=TRUE)."""

    def test_cluster_se(self):
        r = poisson(
            "y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"],
            cluster="firm", vcov_backend="stata",
        )
        npt.assert_allclose(r.std_errors["x1"], R["se_x1_stata"], rtol=0, atol=1e-6)
        npt.assert_allclose(r.std_errors["x2"], R["se_x2_stata"], rtol=0, atol=1e-6)


class TestRPoissonFitStats:
    """Deviance / loglik / pseudo-R2 are identical across tools."""

    def test_deviance(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm")
        npt.assert_allclose(r.deviance, R["deviance"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm")
        npt.assert_allclose(r.llf, R["loglik"], rtol=0, atol=1e-6)

    def test_pseudo_r2(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"], cluster="firm")
        npt.assert_allclose(r.pseudo_r2, R["pseudo_r2"], rtol=0, atol=1e-6)


class TestRPoissonIrr:
    """``.irr()`` = exp(beta) with delta-method SEs (matches Stata/R IRR)."""

    def test_irr_x1(self):
        r = poisson("y ~ x1 + x2", data=DF, fixed_effects=["firm", "year"])
        irr = r.irr()
        npt.assert_allclose(irr.loc[irr["Variable"] == "x1", "IRR"].iloc[0],
                            float(np.exp(R["b_x1"])), rtol=0, atol=1e-6)
