"""R parity tests for OLS post-estimation diagnostics (v1.3).

Reference: R 4.6.1.  The fixture ``diag_estat.json`` is generated by
``tests/r/generate-fixtures/diag_estat.R`` and committed; routine runs read it
as ground truth (see ``r_runner.read_r``).

Covered quantities and their R references (all fit ``lm(y ~ x1 + x2)`` on the
committed ``df_ols`` input):

* **Breusch-Godfrey** (``bg_test``): ``lmtest::bgtest(fit, order=L)``.  bgtest's
  auxiliary regression includes the FULL original design (constant + x1 + x2)
  plus ``L`` lagged residuals, LM = ``n * R^2 ~ chi2(L)`` -- the same
  construction as OE's hand-rolled ``breusch_godfrey`` (OE reimplemented this
  because statsmodels' ``acorr_breusch_godfrey`` silently dropped the design
  matrix).  Tested at order 1 and 2.
* **White's general test** (``white_test``): OE's exact auxiliary replicated in
  R -- ``resid^2`` on ``[x1, x2, x1^2, x2^2, x1*x2]`` each MEAN-CENTERED with an
  auxiliary intercept, LM = ``n * R^2 ~ chi2(5)``.  No off-the-shelf R command
  builds this identical auxiliary, so the ``.R`` generator constructs it by hand.
* **Ljung-Box** (``ljung_box``): ``Box.test(resid(fit), lag=1, type="Ljung-Box")``.
* **Cook's distance** (``cooks_distance``): ``cooks.distance(fit)``.
* **Leverage** (``leverage``): ``hatvalues(fit)``.
* **DFBETAS** (``dfbetas``): ``dfbetas(fit)`` -- exact parity (see
  ``test_dfbetas_vector_strict_parity``).
"""

from __future__ import annotations

import numpy as np
import numpy.testing as npt
import pandas as pd
import pytest

import open_econs as oe
from ..r_runner import R_INPUTS_DIR, read_r

pytestmark = pytest.mark.r

R = read_r("diag_estat")

_FORMULA = "y ~ x1 + x2"


def _fit():
    df = pd.read_csv(R_INPUTS_DIR / "diag_estat_input.csv")
    return oe.ols(_FORMULA, data=df)


class TestRDiagnostics:
    """OLS diagnostics parity against R (lm + lmtest + base influence)."""

    @pytest.fixture(autouse=True)
    def _run(self):
        self.r = _fit()

    # --- Breusch-Godfrey ---------------------------------------------------

    def test_bg_order1_stat(self):
        got = self.r.bg_test(lags=1)
        npt.assert_allclose(got["lm_stat"], R["bg"]["order1"]["lm_stat"], atol=1e-6)

    def test_bg_order1_pvalue(self):
        got = self.r.bg_test(lags=1)
        npt.assert_allclose(got["lm_pvalue"], R["bg"]["order1"]["lm_pvalue"], atol=1e-6)

    def test_bg_order2_stat(self):
        got = self.r.bg_test(lags=2)
        npt.assert_allclose(got["lm_stat"], R["bg"]["order2"]["lm_stat"], atol=1e-6)

    def test_bg_order2_pvalue(self):
        got = self.r.bg_test(lags=2)
        npt.assert_allclose(got["lm_pvalue"], R["bg"]["order2"]["lm_pvalue"], atol=1e-6)

    # --- White's general heteroskedasticity test ---------------------------

    def test_white_stat(self):
        got = self.r.white_test(interaction=True)
        npt.assert_allclose(got["white_stat"], R["white"]["white_stat"], atol=1e-6)

    def test_white_pvalue(self):
        got = self.r.white_test(interaction=True)
        npt.assert_allclose(got["white_pvalue"], R["white"]["white_pvalue"], atol=1e-6)

    def test_white_df(self):
        got = self.r.white_test(interaction=True)
        assert got["df"] == R["white"]["df"]

    # --- Ljung-Box ---------------------------------------------------------

    def test_ljung_box_stat(self):
        got = self.r.ljung_box(lags=1)
        npt.assert_allclose(got["lb_stat"], R["ljung_box"]["lb_stat"], atol=1e-6)

    def test_ljung_box_pvalue(self):
        got = self.r.ljung_box(lags=1)
        npt.assert_allclose(got["lb_pvalue"], R["ljung_box"]["lb_pvalue"], atol=1e-6)

    # --- Cook's distance (full vector) ------------------------------------

    def test_cooks_distance_vector(self):
        got = self.r.cooks_distance()
        assert got.name == "cooks_distance"
        npt.assert_allclose(
            got.values, np.asarray(R["cooks_distance"], dtype=float), atol=1e-6
        )

    # --- Leverage / hatvalues (full vector) -------------------------------

    def test_leverage_vector(self):
        got = self.r.leverage()
        assert got.name == "leverage"
        npt.assert_allclose(
            got.values, np.asarray(R["leverage"], dtype=float), atol=1e-6
        )

    # --- DFBETAS -----------------------------------------------------------

    def test_dfbetas_shape_and_columns(self):
        got = self.r.dfbetas()
        assert isinstance(got, pd.DataFrame)
        assert list(got.columns) == ["Intercept", "x1", "x2"]
        assert got.shape == (int(R["n"]), 3)

    def test_dfbetas_vector_strict_parity(self):
        got = self.r.dfbetas().values
        r_mat = np.asarray(R["dfbetas"], dtype=float)
        npt.assert_allclose(got, r_mat, atol=1e-6)

    def test_dfbetas_gap_magnitude(self):
        """DFBETAS now match R to < 1e-6 (fixed LOO-variance factor 1/(1-h_i)).

        Pins the closed gap so a future regression that widens it past 1e-6 is
        caught.
        """
        got = self.r.dfbetas().values
        r_mat = np.asarray(R["dfbetas"], dtype=float)
        max_gap = float(np.max(np.abs(got - r_mat)))
        assert max_gap < 1e-6, f"DFBETAS gap regressed to {max_gap:g}"

    # --- diagnostics_table -------------------------------------------------

    def test_diagnostics_table_rows(self):
        tbl = self.r.diagnostics_table()
        assert isinstance(tbl, pd.DataFrame)
        assert list(tbl.columns) == ["test", "stat", "pvalue", "df"]
        expected_rows = {
            "jarque_bera",
            "breusch_pagan",
            "white",
            "bgodfrey",
            "ramsey_reset",
            "durbin_watson",
            "ljung_box",
            "condition_number",
        }
        assert expected_rows.issubset(set(tbl["test"]))

    def test_diagnostics_table_white_matches_r(self):
        tbl = self.r.diagnostics_table().set_index("test")
        npt.assert_allclose(
            float(tbl.loc["white", "stat"]), R["white"]["white_stat"], atol=1e-6
        )

    def test_diagnostics_table_bgodfrey_matches_r(self):
        tbl = self.r.diagnostics_table().set_index("test")
        npt.assert_allclose(
            float(tbl.loc["bgodfrey", "stat"]),
            R["bg"]["order1"]["lm_stat"],
            atol=1e-6,
        )

    def test_diagnostics_table_ljung_box_matches_r(self):
        tbl = self.r.diagnostics_table().set_index("test")
        npt.assert_allclose(
            float(tbl.loc["ljung_box", "stat"]),
            R["ljung_box"]["lb_stat"],
            atol=1e-6,
        )
