"""R parity tests for IV / 2SLS (``iv``).

Reference: R's ``AER::ivreg`` + ``sandwich`` (``vcovHC`` / ``vcovCL``).  The
fixture ``iv.json`` is generated by ``tests/r/generate-fixtures/iv.R`` and
committed; routine runs read it as ground truth (see ``r_runner.read_r``).

Convention notes (source-confirmed 2026-07-17, see methodology/linear/iv.md):

* **Coefficient** is the 2SLS estimate and matches ``AER::ivreg`` exactly for
  every covariance type (no toggle needed).
* **R's nonrobust / cluster SEs use a DOF correction that Stata's
  ``ivregress`` does NOT** (R: ``s2 = SSR/(N-K)`` for nonrobust, and the
  ``G/(G-1)`` SSC for cluster; Stata: ``SSR/N`` and no SSC).  OE exposes this
  as the ``debiased`` toggle (default ``False`` = Stata).  These R-parity
  tests therefore pass ``debiased=True`` to align with R's convention per
  rule 15.  The residual ~2.5e-7 gap vs R is independent-implementation noise
  between AER/sandwich and linearmodels, well inside the 1e-6 absolute
  tolerance (rule 2) -- NOT a loosened tolerance.
* **HC1** (``cov_type="HC1"``) matches R ``vcovHC(type="HC1")`` exactly without
  any toggle (R and Stata/linearmodels agree on the HC1 definition).
"""

from __future__ import annotations

import numpy.testing as npt
import pytest

import open_econs as oe
from ..r_runner import read_r

pytestmark = pytest.mark.r

R = read_r("iv")

_FORMULA = "y ~ w | x ~ z1 + z2"


class TestIvRNonRobustDebiased:
    """OE ``cov_type='nonrobust', debiased=True`` matches R ``AER::ivreg``."""

    @pytest.fixture(autouse=True)
    def _run(self, iv_input):
        self.r = R["nonrobust"]
        self.oe_r = oe.iv(_FORMULA, iv_input, cov_type="nonrobust", debiased=True)

    def test_coefficients(self):
        npt.assert_allclose(
            self.oe_r.coefficients.values, self.r["coef"], atol=1e-6
        )

    def test_standard_errors(self):
        npt.assert_allclose(
            self.oe_r.std_errors.values, self.r["se"], atol=1e-6
        )


class TestIvRHc1:
    """OE ``cov_type='HC1', debiased=True`` matches R ``sandwich::vcovHC(type='HC1')``.

    R's ``vcovHC(type="HC1")`` uses ``s2 = SSR/(N-K)``; Stata's ``vce(robust)``
    uses ``SSR/N``.  Both are labeled "HC1" but differ in the variance scale,
    so the R-parity test passes ``debiased=True`` (rule 15 toggle).
    """

    @pytest.fixture(autouse=True)
    def _run(self, iv_input):
        self.r = R["hc1"]
        self.oe_r = oe.iv(_FORMULA, iv_input, cov_type="HC1", debiased=True)

    def test_coefficients(self):
        npt.assert_allclose(
            self.oe_r.coefficients.values, self.r["coef"], atol=1e-6
        )

    def test_standard_errors(self):
        npt.assert_allclose(
            self.oe_r.std_errors.values, self.r["se"], atol=1e-6
        )


class TestIvRHc0:
    """OE ``cov_type='HC0'`` matches R ``sandwich::vcovHC(type='HC0')``.

    linearmodels collapses HC0 to HC1, so OE hand-rolls the MacKinnon-White
    sandwich (``_iv_hc_sandwich``) using the instrument-projected regressors,
    reproducing R's ``sandwich::vcovHC(type="HC0")`` to <=1e-6.
    """

    @pytest.fixture(autouse=True)
    def _run(self, iv_input):
        self.r = R["hc0"]
        self.oe_r = oe.iv(_FORMULA, iv_input, cov_type="HC0", debiased=True)

    def test_coefficients(self):
        npt.assert_allclose(
            self.oe_r.coefficients.values, self.r["coef"], atol=1e-6
        )

    def test_standard_errors(self):
        npt.assert_allclose(
            self.oe_r.std_errors.values, self.r["se"], atol=1e-6
        )


class TestIvRHc2:
    """OE ``cov_type='HC2'`` matches R ``sandwich::vcovHC(type='HC2')``."""

    @pytest.fixture(autouse=True)
    def _run(self, iv_input):
        self.r = R["hc2"]
        self.oe_r = oe.iv(_FORMULA, iv_input, cov_type="HC2", debiased=True)

    def test_coefficients(self):
        npt.assert_allclose(
            self.oe_r.coefficients.values, self.r["coef"], atol=1e-6
        )

    def test_standard_errors(self):
        npt.assert_allclose(
            self.oe_r.std_errors.values, self.r["se"], atol=1e-6
        )


class TestIvRHc3:
    """OE ``cov_type='HC3'`` matches R ``sandwich::vcovHC(type='HC3')``."""

    @pytest.fixture(autouse=True)
    def _run(self, iv_input):
        self.r = R["hc3"]
        self.oe_r = oe.iv(_FORMULA, iv_input, cov_type="HC3", debiased=True)

    def test_coefficients(self):
        npt.assert_allclose(
            self.oe_r.coefficients.values, self.r["coef"], atol=1e-6
        )

    def test_standard_errors(self):
        npt.assert_allclose(
            self.oe_r.std_errors.values, self.r["se"], atol=1e-6
        )


class TestIvRClusterDebiased:
    """OE ``cluster='id', debiased=True`` matches R ``sandwich::vcovCL``."""

    @pytest.fixture(autouse=True)
    def _run(self, iv_input):
        self.r = R["cluster"]
        self.oe_r = oe.iv(_FORMULA, iv_input, cluster="id", debiased=True)

    def test_coefficients(self):
        npt.assert_allclose(
            self.oe_r.coefficients.values, self.r["coef"], atol=1e-6
        )

    def test_standard_errors(self):
        npt.assert_allclose(
            self.oe_r.std_errors.values, self.r["se"], atol=1e-6
        )
