"""R parity tests for ``oe.tobit`` (hand-rolled censored-normal MLE).

Source-verified against R ``AER::tobit`` (the project's primary R reference for
Tobit; ``censReg`` is NOT installed on the dev box — ROADMAP wording updated
accordingly). ``oe.tobit`` matches ``AER::tobit`` to ``1e-6`` on the point
estimates, ``sigma`` (``AER::tobit`` reports ``sigma`` directly via
``summary()$sigma``), the OIM (nonrobust) standard errors, and the
log-likelihood.

Fixtures: ``tests/r/fixtures/expected/tobit.json`` (generated by
``tests/r/generate-fixtures/tobit.R``). Shared input:
``tests/r/fixtures/inputs/tobit_input.csv``.

R fixture keys (left-censored at 0):
    b_x1, b_x2, b_x3     point estimates
    se_x1, se_x2, se_x3  OIM (nonrobust) SEs
    sigma                sigma (== exp(Log(scale)))
    loglik              log-likelihood
    n_left              left-censored obs count
No-censoring variant (keys prefixed ``b2_``, ``se2_``, ``sigma2``, ``loglik2``).

All assertions at ``atol=1e-6`` — nothing loosened (rule 2). Robust SEs for
Tobit are a documented open gap (see FUTURE_WORK.md); only OIM is asserted.
"""

from __future__ import annotations

import numpy.testing as npt
import pandas as pd
import pytest

from open_econs.models.limited.tobit import tobit

from ..r_runner import read_r

pytestmark = pytest.mark.r

R = read_r("tobit")
DF = pd.read_csv("tests/r/fixtures/inputs/tobit_input.csv")


class TestRTobitLeftCensored:
    """Left-censored (left=0, right=Inf) Tobit: coefs / sigma / OIM SE / ll."""

    def test_b_x1(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.coefficients["x1"], R["b_x1"], rtol=0, atol=1e-6)

    def test_b_x2(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.coefficients["x2"], R["b_x2"], rtol=0, atol=1e-6)

    def test_b_x3(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.coefficients["x3"], R["b_x3"], rtol=0, atol=1e-6)

    def test_sigma(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.sigma, R["sigma"], rtol=0, atol=1e-6)

    def test_se_x1(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.std_errors["x1"], R["se_x1"], rtol=0, atol=1e-6)

    def test_se_x2(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.std_errors["x2"], R["se_x2"], rtol=0, atol=1e-6)

    def test_se_x3(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.std_errors["x3"], R["se_x3"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        npt.assert_allclose(r.llf, R["loglik"], rtol=0, atol=1e-6)

    def test_n_left(self):
        r = tobit("y_left ~ x1 + x2 + x3", data=DF, left=0)
        assert r.n_left == int(R["n_left"])


class TestRTobitNoCensoring:
    """No-censoring variant: AER::tobit(left=-Inf, right=Inf) ~ OLS MLE."""

    def test_b_x1(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.coefficients["x1"], R["b2_x1"], rtol=0, atol=1e-6)

    def test_b_x2(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.coefficients["x2"], R["b2_x2"], rtol=0, atol=1e-6)

    def test_b_x3(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.coefficients["x3"], R["b2_x3"], rtol=0, atol=1e-6)

    def test_sigma(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.sigma, R["sigma2"], rtol=0, atol=1e-6)

    def test_se_x1(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.std_errors["x1"], R["se2_x1"], rtol=0, atol=1e-6)

    def test_se_x2(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.std_errors["x2"], R["se2_x2"], rtol=0, atol=1e-6)

    def test_se_x3(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.std_errors["x3"], R["se2_x3"], rtol=0, atol=1e-6)

    def test_loglik(self):
        r = tobit("y_nocens ~ x1 + x2 + x3", data=DF, left=None)
        npt.assert_allclose(r.llf, R["loglik2"], rtol=0, atol=1e-6)
